language: c
before_install:
  - git submodule update --init --recursive
  - sudo apt-get update -qq
  - sudo apt-get install -y cmake libXxf86vm-dev libxml2
install:
  ## Install GLFW
  - git clone https://github.com/glfw/glfw.git
  - cd glfw
  - git checkout 3.0.3
  - cmake -DCMAKE_C_FLAGS=-fPIC -DBUILD_SHARED_LIBS=ON -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_BUILD_DOCS=OFF .
  - make && sudo make install
  - cd -

  ## Installing Rust
  - curl -O http://static.rust-lang.org/dist/rust-nightly-x86_64-unknown-linux-gnu.tar.gz
  - tar xfz rust-nightly-x86_64-unknown-linux-gnu.tar.gz
  - (cd rust-nightly-x86_64-unknown-linux-gnu/ && sudo ./install.sh)
  - rustc -v

  ## Installing SDL2
  - wget http://www.libsdl.org/release/SDL2-2.0.0.tar.gz
  - tar -zxvf SDL2-2.0.0.tar.gz
  - cd SDL2-2.0.0
  - ./configure && make && sudo make install
  - cd -

  ## Installing SDL2-Mixer
  - wget -q http://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.0.tar.gz
  - tar -zxvf SDL2_mixer-2.0.0.tar.gz
  - cd SDL2_mixer-*
  - ./configure && make && sudo make install
  - cd -
script:
  - chmod +x build.sh
  - rustc -v
  - ./build.sh
